default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: noble_beta_development

test:
  <<: *default
  database: noble_beta_test

production:
  <<: *default
  database: noble_beta_production
